name: Build and Sign Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # یک مرحله برای اطمینان از وجود پایتون
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get Flutter dependencies
        run: flutter pub get

      # استفاده از پایتون برای رمزگشایی - مطمئن‌ترین روش
      - name: Decode Keystore using Python
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
        run: |
          import base64
          import os
          
          key_data = os.environ['SIGNING_KEY_BASE64']
          
          # استخراج محتوای خالص base64 از بین هدر و فوتر
          lines = key_data.strip().split('\n')
          if lines[0].strip() == '-----BEGIN CERTIFICATE-----':
              lines = lines[1:-1]
          
          pure_base64 = "".join(lines)

          with open('android/app/my-release-key.jks', 'wb') as f:
              f.write(base64.b64decode(pure_base64))
        shell: python

      # بررسی اینکه آیا فایل کلید با موفقیت ساخته شده است
      - name: Verify Keystore File
        run: |
          if [ -f "android/app/my-release-key.jks" ]; then
            echo "Keystore file created successfully."
            ls -l android/app/my-release-key.jks
          else
            echo "Error: Keystore file was not created."
            exit 1
          fi

      - name: Create key.properties file
        run: |
          echo "storeFile=my-release-key.jks" > android/key.properties
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
      
      - name: Build Signed APK
        run: flutter build apk --release

      - name: Build Signed App Bundle
        run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

