name: Build and Sign Flutter App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Decode Keystore using Python
        env:
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
        run: |
          import base64
          import os
          
          key_data = os.environ.get('SIGNING_KEY_BASE64', '')
          
          lines = key_data.strip().split('\n')
          if lines and lines[0].strip().startswith('-----BEGIN'):
              lines = lines[1:-1]
          
          pure_base64 = "".join(lines)

          with open('android/app/my-release-key.jks', 'wb') as f:
              f.write(base64.b64decode(pure_base64))
        shell: python

      # استفاده از پایتون برای ساخت key.properties - مطمئن‌ترین روش
      - name: Create key.properties using Python
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          import os

          store_password = os.environ.get('STORE_PASSWORD')
          key_alias = os.environ.get('KEY_ALIAS')
          key_password = os.environ.get('KEY_PASSWORD')

          properties_content = f"""
          storeFile=my-release-key.jks
          storePassword={store_password}
          keyAlias={key_alias}
          keyPassword={key_password}
          """

          with open('android/key.properties', 'w') as f:
              f.write(properties_content.strip())
        shell: python

      - name: Build Signed APK
        run: flutter build apk --release

      - name: Build Signed App Bundle
        run: flutter build appbundle --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload App Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

